### ISSUE TITLE
GetSaldo() lub tożsama nazwa ;)

### ISSUE THREAD

**Issue by Borgsc2** [Zaczero/2Captcha#1]
Witam

Mam nadzieje że dobrze wywnioskowałem, i nie muszę pisać łamanym angielskim.

Czy była by możliwość abyś dodał funkcję odczytu salda na 2captcha.com?
Obecnie biblioteka tego nie oferuje (chyba że nie widzę tej opcji) i trzeba korzystać z własnego kodu.

Próbowałem dopisać tą funkcję do źródła i skompilować, ale mimo pozytywnej kompilacji i podmiany biblioteki, pisana aplikacja nie widzi nowo dodanej funkcji w bibliotece. 

Pozdrawiam

**Comment by Zaczero** [comment]
Added in the recent commit
