### ISSUE TITLE
Any luck with Outlook Rotatecaptcha?

### ISSUE THREAD

**Issue by razanjoshi** [Zaczero/2Captcha#17]
According to 2Captcha api, we have to send them the captcha images for RotateCaptchas but on Outlook, the captcha image are being rendered via some JS tricks as we can not even inspect the image url from the canvas. I was wondering if you have any knowledge around it that can help solve my issue.
<img width="498" alt="image" src="https://user-images.githubusercontent.com/4223130/128876898-61719f67-2ca3-41ac-9cfe-1b1f4b912f28.png">

**Comment by Zaczero** [comment]
When using Selenium/Puppeteer/Playwright there should be a way to take the page screenshot. Then, you can get element's bounding box (X,Y,W,H) by calling a small JavaScript code: https://stackoverflow.com/a/11396681, and crop the screenshot accordingly.

-- or --

You can simply dump the canvas to a data URL and retrieve it that way: https://stackoverflow.com/a/3514404. This should be a more elegant (and preferred) approach in my opinion.
