### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by kxslo** [Zaczero/2Captcha#7]
Hello friend like this, I am interested in making your program for 2 captchas, and actually I would like to know how to run it, and what steps should I follow please

**Comment by Zaczero** [comment]
1. Initialize the class with your API key.
2. Execute solving method of your choice.
3. Check if method returned `Success` *(in struct)* and then get the answer from `Response` property.
3.1. If `Success` is false then in `Response` you will have the error message.

Check out this sample code I've written in README:
https://github.com/Zaczero/2Captcha#-sample-code

The return struct is listed here:
https://github.com/Zaczero/2Captcha#and-here-is-the-result-structure-same-for-all-methods
... and the actual code for it:
https://github.com/Zaczero/2Captcha/blob/master/2Captcha/TwoCaptchaResult.cs

**Comment by kxslo** [comment]
I still don't understand, how can I use it from 0, do I have to download any program? enter that code in any program? how is it used if you could teach me please I don't get any exe.

**Comment by Zaczero** [comment]
It's a library to be used with other code. This code by itself does not do anything.
