### ISSUE TITLE
Can you use http instead of https ?

### ISSUE THREAD

**Issue by jojodat** [Zaczero/2Captcha#8]
Hi,
i'd love to use your great lib with other services (like death by captcha or local software like xevil) which provide a 2captcha compatible api endpoint (though they just provide a subset of features)

They usually can be used by setting the 2captcha.com DNS record via hosts file to their IP
But this fails with your lib because they only can provide a http service on port 80 cause of the ssl certificate.

So as original 2captcha also works great via http, i think there would no harm to just use http instead of https

**Comment by jojodat** [comment]
Wow, That was fast.
But can you make it http:// instead of https// ?

**Comment by Zaczero** [comment]
Just set the custom url with http:// at the beginning
